<a href="https://colab.research.google.com/github/profteachkids/StemUnleashed/blob/main/20June_GeneticAlgorithm_TSP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from plotly.subplots import make_subplots
np.set_printoptions(formatter={'float':lambda x: f'{x:0.2f}'})

In [ ]:
rng=np.random.RandomState(123)

In [ ]:
N=10
coords=rng.uniform(0,10, size=(N,2))

In [ ]:
dist=np.sqrt(np.sum((coords[:,None,:]-coords[None,:,:])**2,axis=2))

In [ ]:
def calcdist(seq):
    return np.sum(dist[seq[1:,:],seq[:-1,:]]) + dist[seq[0,:],seq[-1,:]]

In [ ]:
def topn(seq,n):
    dists=calcdist(seq)
    topn_idx=np.argsort(dists)[:n]
    return seq[:,topn_idx], dists[topn_idx]

In [ ]:
popsize = 100
seq=np.zeros((N,popsize), dtype=int)

for popidx in range(popsize):

    remain = list(range(N))

    cur = rng.randint(N)
    seq[0,popidx]=cur
    remain.remove(cur)
    for i in range(1,N-1):
        best2= np.argsort(dist[cur,remain])[:2]
        best=remain[best2[rng.choice([0,1],p=(0.95,0.05))]  ]
        seq[i,popidx]=best
        cur=best
        remain.remove(best)
    seq[-1,popidx]=remain[0]


In [ ]:
top20, dists20 = topn(seq,20)

In [ ]:
top20[0,:].reshape(1,-1)

array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 8, 9, 9]])

In [ ]:
np.r_[top20, np.atleast_2d(top20[0,:])]

array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 8, 9, 9],
       [7, 2, 2, 2, 2, 2, 2, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 1, 2, 2],
       [4, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 7, 7, 7, 7, 3, 0, 0],
       [5, 8, 8, 8, 8, 8, 8, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 7, 7],
       [6, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 4, 4],
       [3, 3, 3, 3, 3, 3, 3, 4, 7, 7, 7, 7, 7, 6, 6, 6, 6, 7, 5, 5],
       [1, 6, 6, 6, 6, 6, 6, 7, 4, 4, 4, 4, 4, 3, 3, 3, 3, 4, 6, 6],
       [8, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 5, 3, 3],
       [9, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 8, 8, 8, 8, 6, 1, 1],
       [2, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 8, 8],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 8, 9, 9]])

In [ ]:
def plotter(seq_plot, dists, nr, nc):
    fig=make_subplots(rows = nr, cols=nc)
    seq = np.r_[seq_plot, np.atleast_2d(seq_plot[0,:])]
    for i in range(seq.shape[1]):
        fig.add_scatter(x=coords[seq[:,i],0], y=coords[seq[:,i],1], row=i//nc+1, col=i%nc +1)
    fig.update_layout(template='plotly_dark', showlegend=False)
    fig.show()
# fig.add_scatter(x=coords[:,0],y=coords[:,1],mode='markers')
# fig.add_scatter(x=coords[seq,0],y=coords[seq,1],mode='lines')
# fig.update_layout(width=800,template='plotly_dark')

In [ ]:
plotter(top20, dists20, nr=4, nc=5)

In [ ]:
rem = list(range(N))
cur = rem[rng.randint(N)]
rem.remove(cur)
seq = np.zeros(N+1, dtype=int)
seq[0]=cur
for i in range(1,N):
    best_idx = np.argmin(dist[cur,rem])
    best = rem[best_idx]
    seq[i]=best
    cur = best
    rem.remove(best)
seq[-1]=seq[0]


In [ ]:
fig=make_subplots()
fig.add_scatter(x=coords[:,0],y=coords[:,1],mode='markers')
fig.add_scatter(x=coords[seq,0],y=coords[seq,1],mode='lines')
fig.update_layout(width=800,template='plotly_dark')

In [ ]:
seq

array([89, 16, 69,  9, 58, 26, 30, 11, 84, 53, 29, 19, 71, 94,  3, 42, 86,
       74, 78, 10, 66, 82, 36, 47, 31, 50, 24, 28, 96, 52, 40,  5, 46,  7,
       80, 72, 92, 18, 83, 23, 45, 62, 79,  2, 64, 54, 22, 60, 87, 32, 85,
       73, 77, 20, 90, 38, 81, 99,  6, 43, 68, 13, 27, 76, 55, 44, 21, 49,
       48, 15, 70,  8, 51, 88, 17,  4, 41,  0, 12, 33, 65, 67, 57, 61, 63,
        1, 34, 14, 95, 39, 75, 91, 56, 25, 35, 59, 98, 97, 37, 93, 89])