<a href="https://colab.research.google.com/github/profteachkids/StemUnleashed/blob/main/Exponential_Poisson_Distributions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import scipy.stats as stats
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio
import pandas as pd
pio.templates.default='plotly_dark'

In [4]:
n=1e6
lmbda = 5000
p = lmbda/n
purchase = np.random.choice([0,1], size=int(1e6), p = [(1-p), p])

In [5]:
purchase_times = np.where(purchase)[0]
time_between = purchase_times[1:]- purchase_times[:-1]

In [7]:
np.histogram(time_between)

(array([2828, 1228,  532,  203,   96,   42,   16,   14,    1,    1]),
 array([1.000e+00, 1.720e+02, 3.430e+02, 5.140e+02, 6.850e+02, 8.560e+02,
        1.027e+03, 1.198e+03, 1.369e+03, 1.540e+03, 1.711e+03]))

In [26]:

fig4=px.histogram(time_between, histnorm='probability density')

fig4.update_layout(width=800,height=600)

In [25]:
px.histogram?

In [22]:
x

array([1.000e+00, 1.720e+02, 3.430e+02, 5.140e+02, 6.850e+02, 8.560e+02,
       1.027e+03, 1.198e+03, 1.369e+03, 1.540e+03, 1.711e+03])

In [ ]:
sales=np.sum(purchase.reshape((int(1e4),100)),axis=1)
sales_poison=stats.poisson(mu=p*100)

In [ ]:
fig4=make_subplots()
fig4.add_histogram(x=sales, name='experimental')
fig4.add_scatter(x=np.arange(5),y=stats.poisson(mu=p*100).pmf(np.arange(5))*1e4, mode='lines', name='Poisson')
fig4.update_layout(width=800,height=600)