<a href="https://colab.research.google.com/github/profteachkids/StemUnleashed/blob/main/exponential_poisson_distributions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import scipy.stats as stats
from plotly.subplots import make_subplots

In [84]:
rng=np.random.RandomState(123)
p=0.01
N_times=int(1e8)
purchase=rng.choice((0,1),size=(N_times), p=(1-p,p))
purchase_times = np.where(purchase)[0]

In [85]:
time_gap=purchase_times[1:]-purchase_times[:-1]

In [86]:
N=time_gap.size

In [87]:
b=np.max(time_gap)
a=0
n=50
dx=(b-a)/n
counts,bins=np.histogram(time_gap,np.linspace(a,b,n))

In [88]:
xplot=np.linspace(0,np.max(bins),500)
fig=make_subplots()
fig.add_bar(x=(bins[1:]+bins[:-1])/2, y=counts, name='experimental')
fig.add_scatter(x=xplot,y=stats.expon.pdf(xplot,scale=1/p)*dx*N,mode='lines',name='exponential-distribution')
fig.update_xaxes(range=(0,400),title='time gap')
fig.update_yaxes(title='counts')
fig.update_layout(width=800,height=600,template='plotly_dark', showlegend=True)

In [106]:
period=1000
purchases_in_period = np.sum(purchase.reshape(-1,period),axis=1)
avg = period*p
periods=purchases_in_period.size

In [94]:
b=np.max(purchases_in_period)
counts,bins=np.histogram(purchases_in_period,b)

In [95]:
counts

array([    3,    52,   235,   742,  1820,  3698,  6452,  9072, 11394,
       12682, 12479, 11315,  9368,  7161,  5388,  3333,  2154,  1258,
         701,   376,   186,    76,    33,    13,     5,     4])

In [96]:
bins

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26.])

In [107]:
stats.poisson.pmf(bins[:-1],mu=avg)*periods

array([4.53999298e+00, 4.53999298e+01, 2.26999649e+02, 7.56665496e+02,
       1.89166374e+03, 3.78332748e+03, 6.30554580e+03, 9.00792257e+03,
       1.12599032e+04, 1.25110036e+04, 1.25110036e+04, 1.13736396e+04,
       9.47803301e+03, 7.29079462e+03, 5.20771044e+03, 3.47180696e+03,
       2.16987935e+03, 1.27639962e+03, 7.09110899e+02, 3.73216263e+02,
       1.86608131e+02, 8.88610150e+01, 4.03913704e+01, 1.75614654e+01,
       7.31727725e+00, 2.92691090e+00])

In [110]:

fig=make_subplots()
fig.add_bar(x=bins[:-1], y=counts, name='experimental')
fig.add_scatter(x=bins[:-1],y=stats.poisson.pmf(bins[:-1],mu=avg)*periods,mode='lines',name='poisson-distribution')
fig.update_xaxes(title='purchases over 1000 time units')
fig.update_yaxes(title='counts')
fig.update_layout(width=800,height=600,template='plotly_dark', showlegend=True)