<a href="https://colab.research.google.com/github/profteachkids/StemUnleashed/blob/main/GroupCompetitionQuestions_25Jun2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import itertools as it

In [37]:
b=np.zeros((3,3,3,3),dtype=np.int8)
b[0,0,0,0]=1
b[0,0,0,2]=1
b[0,0,2,0]=1
b[0,0,2,2]=1
b[0,1,0,2]=1
b[0,1,1,1]=1
b[0,2,0,0]=1
b[0,2,0,1]=1
b[0,2,0,2]=1
b[0,2,1,0]=1
b[0,2,2,0]=1
b[0,2,2,2]=1
b[1,0,1,1]=1
b[1,1,0,1]=1
b[1,1,1,1]=1
b[2,0,2,1]=1
b[2,1,1,1]=1
b[2,1,2,0]=1
b[2,2,0,0]=1
b[2,2,1,1]=1
b[2,2,2,2]=1

In [38]:
def printboard(b):
    br,bc,by,bx=b.shape
    for r in range(br):
        for y in range(by):
            for c in range(bc):
                for x in range(bx):
                    print(f'{"O-X"[b[r,c,y,x]+1]}', end=' ')   #explain in detail
                if c<bc-1:
                    print('  |  ', end='')
            print('\n', end='')
        if r<br-1:
            print('-'*28, end='\n')

In [39]:
printboard(b)

X - X   |  - - X   |  X X X 
- - -   |  - X -   |  X - - 
X - X   |  - - -   |  X - X 
----------------------------
- - -   |  - X -   |  - - - 
- X -   |  - X -   |  - - - 
- - -   |  - - -   |  - - - 
----------------------------
- - -   |  - - -   |  X - - 
- - -   |  - X -   |  - X - 
- X -   |  X - -   |  - - X 


In [40]:
#explain what it.product does, what the * does
pos=np.array(list(it.product(*[[0,1,2]]*4)))

In [41]:
#what do diff0 and diff2 represent?  Why sum over the last axis?  Why the absolute value?  How does broadcasting work here?  Why check for equality to 0 and 2?
diff0=np.sum(np.abs(pos[:,None,:] - pos[None,:,:])==0,axis=-1)
diff2=np.sum(np.abs(pos[:,None,:] - pos[None,:,:])==2,axis=-1)

In [50]:
#what is the relationship between diff2 being 4 and the search for hyper-hyper-diagonal 3-row?
i1,i2=np.where(np.all([diff2==4],axis=0))
i1,i2=(np.c_[i1,i2][i2>i1]).T  #why is this necessary?
step=(pos[i2]-pos[i1])//2  #what is step?
d4 = np.stack([pos[i1], pos[i1]+step, pos[i1]+2*step],axis=1)
d4true=np.sum(b[tuple(d4.reshape(-1,4).T)].reshape(-1,3),axis=1)==3  #explain the innermost reshape, transpose, tuple, outer reshape, and sum equality to 3
nd4=np.sum(d4true)
print(d4[d4true])
print(f'Number of hyper-hyper-diagonal 3-row: {nd4}')

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[0 0 2 2]
  [1 1 1 1]
  [2 2 0 0]]]
Number of hyper-hyper-diagonal 3-row: 2


In [43]:
i1,i2=np.where(np.all([diff2==3,diff0==1],axis=0))
i1,i2=(np.c_[i1,i2][i2>i1]).T
step=(pos[i2]-pos[i1])//2
d3 = np.stack([pos[i1], pos[i1]+step, pos[i1]+2*step],axis=1)
d3true=np.sum(b[tuple(d3.reshape(-1,4).T)].reshape(-1,3),axis=1)==3
nd3=np.sum(d3true)
print(d3[d3true])
print(f'Number of hyper-diagonal 3-row: {nd3}')

[[[0 0 0 0]
  [0 1 1 1]
  [0 2 2 2]]

 [[0 0 0 2]
  [0 1 1 1]
  [0 2 2 0]]

 [[0 0 0 2]
  [1 1 0 1]
  [2 2 0 0]]

 [[0 0 2 0]
  [0 1 1 1]
  [0 2 0 2]]

 [[0 0 2 2]
  [0 1 1 1]
  [0 2 0 0]]

 [[0 1 0 2]
  [1 1 1 1]
  [2 1 2 0]]

 [[0 2 0 1]
  [1 1 1 1]
  [2 0 2 1]]]
Number of hyper-diagonal 3-row: 7


In [44]:
i1,i2=np.where(np.all([diff2==2,diff0==2],axis=0))
i1,i2=(np.c_[i1,i2][i2>i1]).T
step=(pos[i2]-pos[i1])//2
d2 = np.stack([pos[i1], pos[i1]+step, pos[i1]+2*step],axis=1)
d2true=np.sum(b[tuple(d2.reshape(-1,4).T)].reshape(-1,3),axis=1)==3
nd2=np.sum(d2true)
print(d2[d2true])
print(f'Number of diagonal 3-row: {nd2}')

[[[2 2 0 0]
  [2 2 1 1]
  [2 2 2 2]]]
Number of diagonal 3-row: 1


In [45]:
#never start from the beginning on any HW/Test!!!
#why is diff2 and diff0 set equal to 1 and 3 respectively?
i1,i2=np.where(np.all([diff2==1,diff0==3],axis=0))
i1,i2=(np.c_[i1,i2][i2>i1]).T
step=(pos[i2]-pos[i1])//2
d1 = np.stack([pos[i1], pos[i1]+step, pos[i1]+2*step],axis=1)
d1true=np.sum(b[tuple(d1.reshape(-1,4).T)].reshape(-1,3),axis=1)==3
nd1=np.sum(d1true)
print(d1[d1true])
print(f'Number of non-diagonal 3-row: {nd1}')

[[[0 0 0 2]
  [0 1 0 2]
  [0 2 0 2]]

 [[0 1 1 1]
  [1 1 1 1]
  [2 1 1 1]]

 [[0 2 0 0]
  [0 2 0 1]
  [0 2 0 2]]

 [[0 2 0 0]
  [0 2 1 0]
  [0 2 2 0]]]
Number of non-diagonal 3-row: 4
