<a href="https://colab.research.google.com/github/profteachkids/StemUnleashed/blob/main/normal_distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy.stats as stats
from plotly.subplots import make_subplots

In [102]:
rng=np.random.RandomState(125)
N_sample=50
N=int(1e6)
sample=rng.uniform(-1,1,size=(N,N_sample))
# sample = np.where(rng.choice((0,1),size=(N,N_sample)),rng.normal(loc=0,scale=1, size=(N,N_sample)), rng.normal(loc=5,scale=1, size=(N,N_sample)))
means_uniform=np.mean(sample,axis=1)
sample_mean = np.mean(sample)
sample_std = np.mean(np.std(sample,axis=1,ddof=1))

In [103]:
print(f'experimental uniform standard deviation: {mean_sample_std}')
print(f'theoretical uniform standard deviation: {2/np.sqrt(12)}')

experimental uniform standard deviation: 0.576135696782022
theoretical uniform standard deviation: 0.5773502691896258


In [104]:
b=np.max(means_uniform)
a=np.min(means_uniform)
n=50
dx=(b-a)/n
counts,bins=np.histogram(means_uniform,np.linspace(a,b,n))

In [105]:
xplot=np.linspace(a,b,500)
fig=make_subplots()
fig.add_bar(x=(bins[1:]+bins[:-1])/2, y=counts, name='experimental')
fig.add_scatter(x=xplot,y=stats.norm.pdf(xplot,loc=sample_mean, scale=sample_std/np.sqrt(N_mean))*dx*N,mode='lines',name='exponential-distribution')
fig.update_yaxes(title='counts')
fig.update_layout(width=800,height=600,template='plotly_dark', showlegend=True)

In [ ]:
period=1000
purchases_in_period = np.sum(purchase.reshape(-1,period),axis=1)
avg = period*p
periods=purchases_in_period.size

In [ ]:
b=np.max(purchases_in_period)
counts,bins=np.histogram(purchases_in_period,b)

In [ ]:
counts

array([    3,    52,   235,   742,  1820,  3698,  6452,  9072, 11394,
       12682, 12479, 11315,  9368,  7161,  5388,  3333,  2154,  1258,
         701,   376,   186,    76,    33,    13,     5,     4])

In [ ]:
bins

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26.])

In [ ]:
stats.poisson.pmf(bins[:-1],mu=avg)*periods

array([4.53999298e+00, 4.53999298e+01, 2.26999649e+02, 7.56665496e+02,
       1.89166374e+03, 3.78332748e+03, 6.30554580e+03, 9.00792257e+03,
       1.12599032e+04, 1.25110036e+04, 1.25110036e+04, 1.13736396e+04,
       9.47803301e+03, 7.29079462e+03, 5.20771044e+03, 3.47180696e+03,
       2.16987935e+03, 1.27639962e+03, 7.09110899e+02, 3.73216263e+02,
       1.86608131e+02, 8.88610150e+01, 4.03913704e+01, 1.75614654e+01,
       7.31727725e+00, 2.92691090e+00])

In [ ]:

fig=make_subplots()
fig.add_bar(x=bins[:-1], y=counts, name='experimental')
fig.add_scatter(x=bins[:-1],y=stats.poisson.pmf(bins[:-1],mu=avg)*periods,mode='lines',name='poisson-distribution')
fig.update_xaxes(title='purchases over 1000 time units')
fig.update_yaxes(title='counts')
fig.update_layout(width=800,height=600,template='plotly_dark', showlegend=True)