<a href="https://colab.research.google.com/github/profteachkids/StemUnleashed/blob/main/TicTacToeMiniMax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
rng=np.random.RandomState(123)

In [3]:
def check_win(x):
    s=np.concatenate((np.sum(x,axis=0),np.sum(x,axis=1),np.asarray([np.sum(x.diagonal()),np.sum(np.fliplr(x).diagonal())])))
    return 1*np.any(s==3) - np.any(s==-3)

In [17]:
def minimax(board, alpha, beta, depth, player):
    #alpha highest score maximizer has already found
    #beta lowest score minimizer has already found
    win = check_win(board)
    if depth==0 or np.abs(win)==1:
        return win + np.copysign(win,depth) #winning sooner is better
    moves = np.array(np.where(board==0)).T
    if len(moves)==0:
        return 0
    if player==1:
        #got here because the minimizing player which is already guaranteed a maximum of beta
        #is checking if this board position will force the maximizing player to pick a move
        #with value less that beta
        val=-np.inf
        for move in moves:
            move=tuple(move)
            board[move]=1
            val = max(val, minimax(board, alpha, beta, depth-1, -1))
            board[move]=0
            if val >= beta:
                #the maximizing player can find a move better than beta.
                #the minimizing player upon seeing this would not bother with this
                #board position (argument to the function above)
                #no need to check the other possible moves from this board position
                break
            #this alpha is only for the minimax searches in this and deeper levels
            #update the best value that the maximizer is guaranteed.
            alpha = max(alpha,val)
        return val
    else:
        #got here because the maximizing player which is already guaranteed a minimum of alpha
        #is checking if this board position will force the minimizing player to pick a move
        #with value greater than alpha
        val = np.inf
        for move in moves:
            move=tuple(move)
            board[tuple(move)]=-1
            val = min(val, minimax(board, alpha, beta, depth-1, 1))
            board[move]=0
            if val <= alpha:
                #the minimizing player can find a move lower than alpha.
                #the maximizing player upon seeing this would not bother with this
                #board position (argument to the function above)
                #no need to check the other possible moves from this board position
                break
            #this beta is only for the minimax searches in this and deeper levels
            #update the lowest value that the minimizer is guaranteed.
            beta = min(beta,val)
        return val




In [19]:
a=np.zeros((3,3),dtype=np.int8)
print(a)
while True:
    while True:
        move = input('move (col,row):')
        y,x=[int(v)-1 for v in move.split(',')]
        if a[x,y]==0:
            break
    a[x,y]=1
    if(check_win(a) == 1):
        print('YOU WIN')
        break

    moves = np.array(np.where(a==0)).T
    if len(moves)==0:
        print('DRAW')
        break

    minval=np.inf
    minidx=0
    for i,move in enumerate(moves):
        move=tuple(move)
        a[tuple(move)]=-1

        mmx=minimax(a, -np.inf, np.inf, 10, 1)
        if mmx<minval:
            minval=mmx
            minidx=i
        a[move]=0

    a[tuple(moves[minidx])]=-1

    print(a)
    print('-'*10)
    if(check_win(a) == -1):
        print('YOU LOSE')
        break
    if len(moves)==0:
        print('DRAW')
        break

[[0 0 0]
 [0 0 0]
 [0 0 0]]
move (col,row):2,2
[[-1  0  0]
 [ 0  1  0]
 [ 0  0  0]]
----------
move (col,row):3,3
[[-1  0 -1]
 [ 0  1  0]
 [ 0  0  1]]
----------


KeyboardInterrupt: ignored