<a href="https://colab.research.google.com/github/profteachkids/StemUnleashed/blob/main/WaveFrontPlanner_PriorityQueue.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [256]:
import numpy as np
from queue import PriorityQueue

In [22]:
np.set_printoptions(formatter=dict(int=lambda x: f'{x:2d}'))


In [273]:
rng=np.random.RandomState(34)
d = np.zeros((6,6)).astype(np.int32)
start = (0,0)
end = (5,4)
for obs in rng.randint(0,d.size,10):
    d.put(obs,1)
np.multiply.at(d,end,0)
np.add.at(d,end,2)
np.multiply.at(d,start,0)
np.add.at(d,start,99)

print(d)

L=PriorityQueue()
L.put((2,end))
step=0
y_max,x_max = d.shape
while not(L.empty()) and step <100:
    step+=1
    m,(x,y)=L.get_nowait()
    if x+1<x_max and d[y,x+1]==0:
        d[y,x+1]=m+1
        L.put((m+1,(y,x+1)))
    if x>0 and d[y,x-1]==0:
        d[y,x-1]=m+1
        L.put((m+1,(y,x-1)))

    if y+1<y_max and d[y+1,x]==0:
        d[y+1,x]=m+1
        L.put((m+1,(y+1,x)))
    if y>0 and d[y-1,x]==0:
        d[y-1,x]=m+1
        L.put((m+1,(y-1,x)))




[[99  0  0  0  1  1]
 [ 0  0  0  0  0  1]
 [ 0  0  1  0  0  0]
 [ 1  0  0  1  0  0]
 [ 0  0  0  0  0  1]
 [ 0  0  0  1  2  1]]


In [274]:
d

array([[99, 10,  9,  8,  1,  1],
       [10,  9,  8,  7,  6,  1],
       [ 9,  8,  1,  6,  5,  6],
       [ 1,  7,  6,  1,  4,  3],
       [ 7,  6,  5,  4,  3,  1],
       [ 0,  7,  4,  1,  2,  1]], dtype=int32)

In [123]:
d.take(np.array([4,5])+adj)

array([[ 0,  0],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]], dtype=int32)

In [50]:
for x in rng.randint(0,10,(5,2)):
    print(x)

[ 1  5]
[ 6  2]
[ 1  8]
[ 3  5]
[ 0  2]


In [48]:
d.add